### ISSUE TITLE
How to build it as a package of another lib

### ISSUE THREAD

**Issue by eladyaniv01** [hjweide/pyastar#10]
first of all, I would like to say,  you have done amazing work!

I am making use of your `pyastar` here  https://github.com/eladyaniv01/SC2MapAnalysis

however I want to give credit where credit is due,  and I cannot find a way to just add it to the installation process

something gets missed in the build, (and since it's not published a build must be done on the install , right ? )  
the only solution I have found so far is to create python installation scripts 

https://github.com/eladyaniv01/SC2MapAnalysis/blob/master/install.py

the current solution works, 
but I had to edit some of your code and place it in my project directory,  
I would much rather install it as is,  and give you full credit for the great pathfinding engine that is being used.

Let me know if you know how to solve this <3

**Comment by hjweide** [comment]
Thanks for your kind words!  Great to know I was able to help you.

When I need to use this in my own projects I just add it to the `requirements.txt` like this:

```pyastar @ git+git://github.com/hjweide/pyastar.git@master#egg=pyastar```

That way it gets installed directly from the repo when my project gets installed.  Maybe that works for you too?

**Comment by eladyaniv01** [comment]
`pyastar @ git+git://github.com/hjweide/pyastar.git@master#egg=pyastar` Worked!  thank you so much!

I would go with **pyastarcpp**

because I was looking for exactly that (python interface, c/cpp implementation)

**Comment by hjweide** [comment]
> pyastar @ git+git://github.com/hjweide/pyastar.git@master#egg=pyastar Worked! thank you so much!

Thanks for confirming!  I'll add this to the README.

**Comment by eladyaniv01** [comment]
allow me <3

**Comment by eladyaniv01** [comment]
thank you <3
