### ISSUE TITLE
Before astar path planning, how do you set the robot size?

### ISSUE THREAD

**Issue by jeonds1127** [hjweide/pyastar#12]
Before astar path planning, how do you set the robot size?

**Comment by hjweide** [comment]
What do you mean by "robot size"?

**Comment by jeonds1127** [comment]
In the uploaded code, I can get a path that a 1x1 pixel robot can pass.
Do you know how to get path for 2x2, 3x3 pixel robots?

**Comment by hjweide** [comment]
A shortest path problem is just an abstraction. There is no robot. Each
entry in the path is just a node in a graph. If you want to enforce
constraints such as each entry in the path being multiple nodes (like 3x3)
then you'd have to transform the graph before solving the shortest path
problem.

**Comment by jeonds1127** [comment]
Thank you for taking the time to help me. It was a great help :)
