### ISSUE TITLE
suboptimal paths with allow_diagonal=True

### ISSUE THREAD

**Issue by dHonerkamp** [hjweide/pyastar#13]
Hi, thanks a lot for this implementation.

Unfortunately I am running into some weird paths if I set allow_diagonal to true. My map is 100x100 with walls around the edges with cost 1001, one obstacle, also cost 1001, and all other tiles set to weight 1.

Below you can see the output with allow_diagonal=False (left) which is as expected and allow_diagonal=True (right) which is suboptimal. Furthermore changing the weight of the empty space to 2 or other small integers results in even worse paths. Starting point is in the middle, goal is the one achieved by the planner.

![Screenshot from 2021-02-08 18-05-17](https://user-images.githubusercontent.com/31133390/107256013-39c7af00-6a39-11eb-9872-f258d5c1855a.png)

Do you have an idea what the issue could be or if I am using it incorretly?

How I am calling the library:
```
        weights = np.asarray(self._map._floorplan_img).copy().astype(np.float)
        # weights need to be at least 1 for pyastar -> set walls to high value, all other to low values
        weights[weights.astype(np.bool)] = 1000
        weights += 1
        self._weights = weights
```

```
        path_pixels = pyastar.astar_path(self._weights, astar_start, astar_goal_wrist, allow_diagonal=True)
```

**Comment by dHonerkamp** [comment]
Actually, just after opening this issue I had the deciding insight: it seems the weights _have_ to be np.float32, not np.float. So feel free to close this again.

On a sidenote: it would be nice to be able to specify a higher cost for moving diagonally as I am getting a lot of diagonal movements where it would be possible to just go straight, as e.g. here:

![Screenshot from 2021-02-08 18-26-20](https://user-images.githubusercontent.com/31133390/107257723-46e59d80-6a3b-11eb-9f40-93c1d4849ff7.png)

**Comment by hjweide** [comment]
> it seems the weights have to be np.float32, not np.float

Correct -- this is the datatype expected by the underlying C++ implementation.  Maybe there should be an explicit check of the datatype enforced.

> it would be nice to be able to specify a higher cost for moving diagonally as I am getting a lot of diagonal movements where it would be possible to just go straight, as e.g. here

This implementation defines the shortest path as the path that minimizes the sum of pixels traversed, so making diagonal moves more expensive doesn't really fit with that.  However, if you're working with grids with large areas of uniform-cost but prefer straight paths over diagonal ones it should be a fairly straightforward change to give precedence to straight paths by changing the order in which neighbors are added to the priority queue:
https://github.com/hjweide/pyastar/blob/master/src/cpp/astar.cpp#L92

But if you're working with uniform-cost grids, why not use [jump point search](https://en.wikipedia.org/wiki/Jump_point_search) instead? :)

**Comment by dHonerkamp** [comment]
Thanks for your reply. An automatic check or a note in the readme might indeed be helpful :)
Makes sense in the pixel perspective. I will look at what you've mentioned.
