### ISSUE TITLE
How can I run this in windows

### ISSUE THREAD

**Issue by Saminhasan5220** [hjweide/pyastar#5]
I ran nmake to make astar.so.

When I tried to run the example.py, i got this error -

         File "pyastar.py", line 9, in <module>
            lib = ctypes.cdll.LoadLibrary(join(dirname(fname), 'astar.so'))
          File "C:\Program Files\Python37\lib\ctypes\__init__.py", line 442, in LoadLibrary
            return self._dlltype(name)
          File "C:\Program Files\Python37\lib\ctypes\__init__.py", line 364, in __init__
            self._handle = _dlopen(self._name, mode)
        OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by hjweide** [comment]
Unfortunately this version is only supported on Linux.  I have a fix available to make it work on Windows and hope to release it soon.

**Comment by YoonAddicting** [comment]
Hi, are there any news on the Windows compatible version?

**Comment by m3talstorm** [comment]
The above error is typical when compiling on one platform (like Linux) and trying to run it on windows.

Run make on the windows machine.

**Comment by hjweide** [comment]
> Hi, are there any news on the Windows compatible version?

I made some changes recently that moved building the shared object file to `setup.py` instead of a `Makefile`, and was able to get it running on Windows after install Cython manually.  See if that works for you too:
```bash
pip install Cython
pip install .
```
