### ISSUE TITLE
How to make it run on Windows, not on Linux only

### ISSUE THREAD

**Issue by AlexeyVolosnikov** [hjweide/pyastar#6]
I came back for this algorithm. It doesn't run on windows because most of the users use python 64 bit, but it requires python 32 bit version. Linux usually use 32bit by default, but windows 64 and that was the reason, so If anyone want to use it on windows just use python32bit version (separate conda envs will help). You can add this info to the readme for windows users.

**Comment by hjweide** [comment]
I made some changes recently and was able to get it working on Windows:
```bash
pip install Cython
pip install .
```
